[project]
name = "lb-template-mcp-sqlite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "fastmcp>=2.13.0.2",
]
[tool.setuptools]
py-modules = ["server", "client"]